### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by asleepwalker** [asleepwalker/typographie#2]
- [x] Конвертирование в отдельный класс
- [x] Поля ввода должны адаптироваться под высоту окна браузера
- [x] Не «исправлять» пунктуацию в URL
- [x] Не «исправлять» пунктуацию в e-mail
- [x] Не добавлять пробел перед тире в начале строки
- [x] Расстановка тэгов параграфа в конверторе
- [x] Не ломать смайлики корректором пунктуации
- [x] Не ломать дроби корректором пунктуации
- [x] Мигрировать на Backbone.js
